#!/bin/sh /etc/rc.common

START=99
STOP=1
PROG=/root/scripts/backup_on_change.sh

start() {
    echo "Starting backup on change service"
    # Execute the script directly in the background
    $PROG &
}

stop() {
    echo "Stopping backup on change service"
    # Use killall on the script name (which is always accurate on OpenWrt's ps list)
    killall $(basename $PROG)
}
